spring:
  h2:
    console.enable: true
  datasource:
    url: jdbc:h2:mem:crudappdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true